### ISSUE TITLE
No active connection

### ISSUE THREAD

**Issue by ItsBlackHood** [Ventile-Client/Download#1]
i keep receiving no actie connection even i retry many times it still the same how can i fix it??????

**Comment by yyp-V** [comment]
check if your Firewall is blocking Ventile from connecting to the Internet. 
Since Its downloading stuff like the cosmetics from a github page, it needs to have an active internet connection. 
Ventile is not a verified app, wich could make ur fireawall think its a virus installing malware or something on your computer.
I recommend checking ur antivirus and firewall and make an exception.

**Comment by yyp-V** [comment]
if it keeps saying that pelase create a new issue.
